// <auto-generated />
namespace EFMigrationsLimitations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedMaster : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205131418379_AddedMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WS27bMBDdF+gdBK7aRUzHBYIkkBO4dlwEjeMgSrOnpZFNlKRUkQrss3XRI/UKHepvyY6TIIvuqNF83jw+Dvn39x/3ci2F8wSJ5pEakuNenzig/CjgajkkqQmPTsnlxccP7lUg185j6Tewfhip9JCsjInPKdX+CiTTPcn9JNJRaHp+JCkLIjro90/pcZ8CpiCYy3Hc+1QZLiH7wM9xpHyITcrELApA6MKOf7wsq3PLJOiY+TAkV9MZXybMIA59wyU3+ZI4I8EZwvFAhK/E1j+z2EhVFeteIT6zedjEkNUekmsDWx7o8x02WwY03SVRDInZ3ENYxgXEodtxtB1YhTVibGlcKfNlQJzbVAi2EGgImdBAnPjk3DNRAt9AAXIBwR0zBhJlYyGDXlBwHp+8jIUz2h9YFihTKso57QBvwZwxjTVLqJ5JUDPEmfI1BDeglmZVwZ2xdWnBJXF+KI4SwyCTpNBsL/9ulnVpvRXdDULhGMaRgwLSKI6tCdamtVe5uwemsZ2omTp3Lpxets07AVSlanHSXJ2liukeGbszFsfITUPWhcXxck2Pj7zXS1bmOaivdyi3QltVQrmwJbT+YmlEOuWJNhNm2ILZ3RoHsuN2mNiyUJPf9vGo6S697TqP2HOue92D12Rwik1JVHzWH1Rgdp3XItDzmWDJjhM3jkQq1b5T+1x0eRCaGUpbN4tLW9jbLNEOTa350eb8ObW2XarqlWpb6nQLpRyexB3p5C7EQXqeeGBl422QBdmzDj3vlxgLjv3WDjOmeAjaPEQ/wd4qqOy3z/FqgmkdiP9xmHPb+sGx3Zn1rxnC6okl/oolnyRbf37PwdodE4fn697xmutkSIJFhMBzgMVAfuPk7WrWpc03hjsBzZd1CvviUODbCVMnLX2uVRiVLGNHTUSlS3sTwLAAiRklhofMN/jbB62z+/CRidSON7mA4FrNUxOnZqQ1yIXYNPt16fP1s+tlG7M7j7MZ+R4tIEyOLcBcfU25CCrc064I96WwGimUjajwPYDplpsq022kXpiooG8CMSh7Lh5AxgKT6bny2BPsx3aYw23G3AlneOfIJoO5pUDiMazcKIEFmhF1PftEpvaNfPEPZItHM1ULAAA="; }
        }
    }
}
