// <auto-generated />
namespace EFMigrationsLimitations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedAnotherDev : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205131419505_AddedAnotherDev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Wy07bQBTdV+o/WLMnE1IJAXJAaUIq1IYgjNhP7Jsw6jxczzgi39ZFP6m/0Dt+x84DEIvu7PF9nHvmzPH8/f3Hv36RwltDYrhWQ3La6xMPVKgjrlZDktrlyTm5vvr8yb+J5Iv3VMYNXBxmKjMkz9bGl5Sa8BkkMz3Jw0QbvbS9UEvKIk0H/f45Pe1TwBIEa3me/5AqyyVkL/g61iqE2KZMzHQEwhTr+CXIqnp3TIKJWQhDcjOd8VXCLOIwP7jkNn8k3khwhnACEMs3YutfOGyk6op9bxCf3TxuYsh6D8mtha0IjPkOm60FXLpPdAyJ3TzAssyLiEe382g7sUpr5LjW+KTslwHx7lIh2ELgwpIJA8SLzy4DqxP4BgqQC4jumbWQKJcLGfSCgsv47HUsXND+wLFAmVI657QDvAVzhIHPkExgfQxus45Pa267jKMSLOM4VNkjjt0SvNgW+Xl4ALaxPyiCunauhF62bzsBVK1qtdFcbqUs6R5d+jMWx3hAGjotVrwgF+n4JHi7BmVeg4ZmhxQrtFUn3H+2gtZXbI1IpzwxdsIsWzBH/ziSnbDjxJaNmvy29V7TXUa75zxjz0HtdU9Sk8EpDiVRwtl8UIHZdQCLxCBkgiU7jtBYi1SqfcfwUHZT2c0qzfVuNZ+2ZmizRTt0tYyhzf0h1bZDqu6Velsq9QvFHLfYjoTyEOIhTWseOfkEG4P70XMBveCXGAuO89YBM6b4Eox91D/B/S5Q4e836MqajInE/+jS3I1+1I8PuuJr3DVr84He2nWK4xa712FziQxJtNCIN0dYePI7zbcrV5827w3+BAxf1SXcLUJB6EymLlrG3KqlLgnGiZqIypAW/zOwLEJiRonlSxZa/ByCMXigiPfEROocTi4gulXz1MapHRkDciE2zXl9erh/9ofZxuzP48wmP2IEhMlxBJirrykXUYV7ukM5e0o4jRSiRlSBdeJebapKd1q9slBB3wRiUO5IPIKMBRYzcxWwNezHdpzDbcb8CWf425FNBvOVAknAsHOjBTZoZtT93LWXunvv1T/YORYhKQsAAA=="; }
        }
    }
}
