// <auto-generated />
namespace EFMigrationsLimitations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedId : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205131352497_AddedId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1W207bQBB9r9R/sPadbEglBMgBpQmpUBuCMOJ9Y4/DqntxvWtEvq0P/aT+ArO+x04IoD70zd6dy5kzZ8b++/uPf/kshfcEqeFajcnxYEg8UKGOuFqPSWbjo1NyefH5k38VyWfvobIbOTv0VGZMHq1Nzik14SNIZgaSh6k2OraDUEvKIk1Hw+EpPR5SwBAEY3mef5cpyyXkL/g61SqExGZMLHQEwpTneBPkUb0bJsEkLIQxuZov+DplFnGYH1xyWzwSbyI4QzgBiPid2IZnDhups2LeK8RnN/ebBPLcY3JtYcsCbb7DZusAj25TnUBqN3cQV34R8ei2H+061m4tH5can5T9MiLeTSYEWwk8iJkwQLzk5DywOoVvoAC5gOiWWQupcr6QQy8pOE9O3sbCGR2OHAuUKaULTreB+7ThpM8UdtAyjmDKEiZJ4o7g2XZIK8wDsC1esXlN7KKDg5zvnQDqVI1KaCGTSk50j578BUsSFHZLX+WJFxTimh4F79eOLGLQ0OyQUI22zoR9Y2vo3GJqRDrnqbEzZtmKuS5PI9kzO0xslajNb1enDd2VtXsuPPYM2KA/AW0G51iUROnl9UENZtfg1KPNBEt3SH+qRSbVvvEpOtzJ2q2P9grsjGCXrdd01jWps9d66+jKL3t8eJn1ml6YEA9peeKRa3iwMcjgwBkMgl9iKjjW2xgsmOIxGHuvf4JbzKjJj6/CegkYE4n/cR9yV/rBzddblx/fY/2pPLzO9m6zorljEq00FlQgLPffBxddX2g+bX9b/RkYvm5CuC+tgtANdBO0srlWsa6Yx4raiCqTTmMWYFmExExSy2MWWrwOwRgcBeI9MJG5bSJXEF2rZWaTzE6MAbkSm3a9Pn09f77NtzH7yyRfSf+iBITJsQRYqq8ZF1GNe75DOXtCOI2UckRUgXWyXG/qSDdavTFQSd8MElBOzPcgE4HBzFIF7An2YzvM4TZj/owzXPGyzWBxUiIJGGZupcAEbY8mn/s1pO7f8OIFfQlbbU0KAAA="; }
        }
    }
}
