// <auto-generated />
namespace EFMigrationsLimitations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedAnotherDev2 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201205131431140_AddedAnotherDev2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XzW7aQBC+V+o7WHtqD2UJlaIkMokohCpqCFGc5r7YA6y6u3a9awTP1kMfqa/QWf9jBwhpK/Vmj+fn28/zzdi/fvx0r9ZSOCuINQ9Vn5x0usQB5YcBV4s+Scz8wxm5unz7xr0O5Np5Kvx61g8jle6TpTHRBaXaX4JkuiO5H4c6nJuOH0rKgpD2ut0zetKlgCkI5nIc9yFRhktIb/B2GCofIpMwMQkDEDq34xMvzercMQk6Yj70yfV4whcxM4hD33LJTXZJnIHgDOF4IOZHYuueW2ykrIp1rxGf2TxuIkhr98mNgS0P9PkCmy0Dmu7jMILYbB5gXsQFxKHbcbQZWIbVYmxpvFLmY484d4kQbCbQMGdCA3Gi0wvPhDF8BgXIBQT3zBiIlY2FFHpOwUV0+jIWzmm3Z1mgTKkw47QFvAFzwjTWLKB6JsaeIc6YryG4BbUwyxLuhK0LC14S56vi2GIYZOIE6sfL7veXHSC+JcQjWP3j0i6tuqDdG9izhnGkv4AVRdYEa9Nok8zdA1PrJGzXKnfWs520w54FUJaqdEEzYRQCojsU5E5YFCE3NUXlFsfL5DT84B2vFpnloL5+RjQl2rISdipbQOMplkakYx5rM2KGzZh9W8NAttwOE1sUqvPbVGZFd+Ftr7OIHSOl09Z8ncExHkqi2NLzQQnmuVGRB3o+Eyx+RuzDUCRS7RoY+6ILDdYzFLaXZ6lLqp6pbm9nc2mDiSbntEV6YxA23+C+3m+6lNVLDTR63c377vBKaTVi5kIcpGnFA9uE3gY5lR3r0PG+i6HgeN7KYcIUn4M2j+E3sOsRdfL6hVSOYq0D8T9uJW6PfnD/tJbWMdtErVjsL1n8TrL1+z/fEEekO27qt2fY4eG/c/ZnbdcnwSxE4BnAfFu8ci20JeDS+reXOwLNF1UK+yWmwLfjr0pa+NyoeVgwjSeqIypcmu8UDAuQmEFs+Jz5Bh/7oHW6rJ+YSOzslTMIbtQ0MVFiBlqDnIlN/bwu3V8/3X3bmN1plA7wv3EEhMnxCDBVnxIughL3uN3Tu1LYHsmFgqjwYwXTLTZlprtQvTBRTt8IIlBWZo8gI4HJ9FR5bAW7sR3mcJsxd8QZLkRZZzCz5Eg8hpVrJbBAPaKqZ38dqP13uPwNypOZIG0MAAA="; }
        }
    }
}
